### ISSUE TITLE
Posible ampliamiento del punto "git como fuente de verdad principal" 

### ISSUE THREAD

**Issue by Intimaria** [Mikroways/gitops-workflow#1]
Sugerencia para clarificar porque usamos git como fuente de verdad principal, se podría ampliar el punto

https://github.com/Mikroways/gitops-workflow/blob/a12ec21bb928ce8e7efbe50918ab1e0fb63fe209/docs/index.md?plain=1#L24-L25

Esto significa  que toda la infraestructura puede ser versionada, auditada y fácilmente revertida si es necesario, garantizando implementaciones consistentes y reproducibles. Permite ágil recuperación ante errores. Se versiona la configuración y estado de la infraestructura canónica.

**Comment by chrodriguez** [comment]
Perfecto! Si podes, agrega el texto y crea un PR
